### PR TITLE
added theme-color tags to some timing and run pages

### PR DESCRIPTION
**Pull request by TransportVic**
Add theme colours for mobile browsers to match the specific colour assigned in the PTV Style Guide

Done:

- [x] Metro Trains - timings
- [x] Metro Trains - runs
- [x]  V/Line (coach) - timings
- [x] Ferry - timings
- [x] V/Line (rail) - timings
- [x] V/Line (rail) - runs
- [x] Ferry - runs
- [x] Trams - timings
- [x] Trams - runs
- [x] Buses - runs
- [x] Buses - timings
- [x]  V/Line (coach) - runs

### CODE REVIEW

**Comment by TransportVic** [comment]
Not 100% sure how PRs work, but is there a checkbox to allow commits from maintainers? I've got some commits that can fix up the remaining stuff

**Comment by melbournefan** [comment]
Pretty sure the access tab in the repo settings would able to add myself as a maintainer?? if that's what ur asking, then there's apparently a tab where you can set the individual permissions based on the maintainer, tho I've never done this before so don't count me on it.. unless u're saying that u want to commit to my repo???

**Comment by TransportVic** [comment]
There's supposed to be a checkbox on this page

I think this is what we're looking for
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by melbournefan** [comment]
Ehh, looks like because the PR was created by urself that I'm unable to give permissions as i'm not the creator of the PR..... Maybe close this PR and I may be able to create a PR on my repo instead??

**Comment by melbournefan** [comment]
It just links me back to this one btw

**Comment by TransportVic** [comment]
Alright I'll close this one and we try again

**Pull request closed without merging**
